import { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'en' | 'vi';

const translations = {
  en: {
    // Brand
    brandName: 'SmartAttend',
    brandTagline: 'Face Recognition Attendance System',
    systemFull: 'Smart Attendance System using Face Recognition and Liveness Detection',

    // Landing navbar
    navFeatures: 'Features',
    navHowItWorks: 'How it works',
    navUsers: 'Target Users',
    navPricing: 'Pricing',
    navLogin: 'Login',
    navGetStarted: 'Get Started Free',

    // Hero
    heroTitle1: 'Smart Attendance',
    heroTitle2: 'System',
    heroTitle3: 'powered by AI',
    heroSubtitle: 'Instant face recognition · Liveness detection to prevent fraud · Real-time reports. The most modern attendance solution for schools and businesses.',
    heroCta1: 'Get Started Free',
    heroCta2: 'Watch demo',
    stat1Val: '500+', stat1Label: 'Schools',
    stat2Val: '50K+', stat2Label: 'Students',
    stat3Val: '98.7%', stat3Label: 'Accuracy',
    stat4Val: '< 1s', stat4Label: 'Recognition time',

    // Trust bar
    trustedBy: 'TRUSTED BY LEADING ORGANIZATIONS',

    // Features
    featuresTag: 'FEATURES',
    featuresTitle: 'All in one platform',
    featuresSubtitle: 'From face recognition to automated reports — SmartAttend provides every tool you need to manage attendance efficiently.',
    feat1Title: 'AI Face Recognition',
    feat1Desc: 'Advanced face recognition technology with up to 98.7% accuracy, working in all lighting conditions.',
    feat2Title: 'Liveness Detection',
    feat2Desc: 'Detect and prevent fraud by verifying real persons through natural movements like blinking and head turns.',
    feat3Title: 'Real-time Dashboard',
    feat3Desc: 'Monitor attendance instantly with visual charts, class statistics and smart alerts.',
    feat4Title: 'Reports & Analytics',
    feat4Desc: 'Export detailed PDF/Excel reports, analyze trends and forecast attendance rates for each class.',
    feat5Title: 'Multi-layer Security',
    feat5Desc: 'End-to-end data encryption, role-based access control: Admin, Teacher, Student.',
    feat6Title: 'Cross-platform',
    feat6Desc: 'Works on all browsers and devices. No software installation needed, just an internet connection.',

    // How it works
    howTag: 'HOW IT WORKS',
    howTitle: 'Attendance in just 3 seconds',
    howSubtitle: 'Simple, fast and highly secure process.',
    step1Title: 'Open Camera',
    step1Desc: 'Student stands in front of the attendance camera. The system automatically detects the face within 1 second.',
    step2Title: 'Verify Identity',
    step2Desc: 'AI performs liveness check (blink, head turn) to ensure it\'s a real person, not a photo or video.',
    step3Title: 'Record Attendance',
    step3Desc: 'Attendance is instantly recorded in the system, notifying teacher and parents immediately.',

    // Target users
    usersTag: 'TARGET USERS',
    usersTitle: 'Suitable for all organizations',
    userSchoolName: 'Schools',
    userSchoolDesc: 'Complete solution for student attendance management from kindergarten to high school with school management system integration.',
    userSchoolStat1: '500+ schools using', userSchoolStat2: 'Save 3h/day', userSchoolStat3: '99.2% parent satisfaction',
    userSchoolBadge: 'Most Popular',
    userUniName: 'Universities & Colleges',
    userUniDesc: 'Manage student attendance for thousands of classes, integrated with LMS and student portals.',
    userUniStat1: '120+ universities', userUniStat2: 'Support 50,000+ students', userUniStat3: 'Open API for LMS',
    userUniBadge: 'Premium',
    userCorpName: 'Businesses',
    userCorpDesc: 'Time-attendance system with face recognition for offices, factories and corporate training centers.',
    userCorpStat1: '200+ businesses', userCorpStat2: 'HR system integration', userCorpStat3: 'Automated payroll reports',
    userCorpBadge: 'Enterprise',
    learnMore: 'Learn more',

    // Testimonials
    testimonialsTag: 'TESTIMONIALS',
    testimonialsTitle: 'Loved by thousands of teachers',
    t1Role: 'Head of IT, Vietnam National University',
    t1Text: 'SmartAttend has saved us more than 3 hours a day in attendance management. The interface is intuitive and easy to use even for senior faculty.',
    t2Role: 'Homeroom Teacher, Chu Van An High School',
    t2Text: 'Students no longer cheat on attendance. Parents are also reassured because they receive notifications immediately when their child is absent.',
    t3Role: 'HR Director, FPT Software',
    t3Text: 'Easy integration with our HR system. The reporting feature is very powerful, making payroll calculation more accurate and transparent.',

    // CTA
    ctaBadge: 'Free 30-day trial, no credit card required',
    ctaTitle1: 'Start today',
    ctaTitle2: 'Free, no commitment',
    ctaSubtitle: 'Join 500+ schools and businesses using SmartAttend. Setup in 5 minutes.',
    ctaBtn1: 'Create Free Account',
    ctaBtn2: 'Login to system',

    // Footer
    footerProduct: 'Product',
    footerCompany: 'Company',
    footerSupport: 'Support',
    footerAbout: 'About us',
    footerBlog: 'Blog',
    footerCareers: 'Careers',
    footerPress: 'Press',
    footerDocs: 'Documentation',
    footerHelp: 'Help Center',
    footerContact: 'Contact',
    footerPrivacy: 'Privacy Policy',
    footerDesc: 'AI-powered smart attendance system for schools and businesses.',
    allSystemsNormal: 'All systems operational',
    copyright: '© 2026 SmartAttend. Built in Vietnam 🇻🇳',

    // Auth — Login
    loginWelcome: 'Welcome back',
    loginSubtitle: 'Enter your account credentials',
    loginEmail: 'Email',
    loginEmailPlaceholder: 'email@school.edu',
    loginPassword: 'Password',
    loginPassPlaceholder: '••••••••',
    loginForgot: 'Forgot password?',
    loginBtn: 'Login',
    loginNoAccount: "Don't have an account?",
    loginRegisterLink: 'Register now',
    loginDemoLabel: '⚡ QUICK DEMO LOGIN',
    loginDemoAdmin: 'Administrator',
    loginDemoTeacher: 'Teacher',
    loginDemoStudent: 'Student',
    loginDemoOnClick: '1-click demo',
    loginError: 'Incorrect email or password. Please use a demo account below.',
    loginBrandFeature1Title: 'High Security',
    loginBrandFeature1Desc: 'End-to-end data encryption',
    loginBrandFeature2Title: 'Easy to Use',
    loginBrandFeature2Desc: 'Intuitive interface for everyone',
    loginBrandFeature3Title: 'Real-time',
    loginBrandFeature3Desc: 'Instant attendance updates',
    loginAsRole: 'Logging in as',
    loginAllSystems: 'All systems operational',

    // Auth — Register
    registerStep1: 'Select Role',
    registerStep2: 'Personal Info',
    registerStep3: 'Register Face',
    registerStepOf: 'Step',
    registerStepOf2: 'of 3:',
    registerWhoAreYou: 'Who are you?',
    registerWhoDesc: 'Select your role so we can set up the right account for you.',
    registerRoleStudent: 'Student',
    registerRoleStudentDesc: 'View attendance history, track your own attendance rate.',
    registerRoleTeacher: 'Teacher / Lecturer',
    registerRoleTeacherDesc: 'Manage class attendance, view reports and start attendance sessions.',
    registerCreateAccount: 'Create',
    registerAccount: 'Account',
    registerFillInfo: 'Fill in the information below',
    registerName: 'Full Name',
    registerNamePH1: 'Dr. John Smith',
    registerNamePH2: 'Jane Doe',
    registerEmail: 'Email',
    registerEmailPH: 'email@school.edu',
    registerFaculty: 'Faculty / Department',
    registerFaculty1: 'Faculty of Information Technology',
    registerFaculty2: 'Faculty of Economics',
    registerFaculty3: 'Faculty of Foreign Languages',
    registerFaculty4: 'Faculty of Engineering',
    registerClassCode: 'Class Code',
    registerClassPH: 'CS-301',
    registerPassword: 'Password',
    registerPasswordPH: 'Minimum 8 characters',
    registerConfirmPass: 'Confirm Password',
    registerConfirmPH: 'Re-enter password',
    registerCreateBtn: 'Create Account',
    registerPassMismatch: 'Passwords do not match.',
    registerBack: 'Back',
    registerAlreadyHave: 'Already have an account?',
    registerLoginLink: 'Login',
    registerFaceTitle: 'Register Face',
    registerFaceDesc: 'Register your face to use the automatic attendance feature. You can skip this step and do it later.',
    registerFaceBtn: 'Turn on camera to register now',
    registerFaceSkip: 'Skip, register later',
    registerTerms: 'By registering, you agree to our',
    registerTermsLink: 'Terms of Service',
    registerAnd: 'and',
    registerPrivacyLink: 'Privacy Policy',

    // Admin Layout
    adminRole: 'Administrator',
    adminLoggedInAs: 'Logged in as',
    adminSideNavOverview: 'Overview',
    adminSideNavAttendance: 'Attendance',
    adminSideNavClasses: 'Classes',
    adminSideNavStudents: 'Students',
    adminSideNavReports: 'Reports',
    adminSideNavAlerts: 'Alerts',
    adminSideNavSettings: 'Settings',
    adminLogout: 'Logout',
    adminBreadcrumbHome: 'Home',
    adminNotifTitle: 'Notifications',
    adminMarkRead: 'Mark all read',
    adminNotif1: 'Unknown face detected — Camera A',
    adminNotif2: 'Liveness check failed — Room 202',
    adminNotif3: '3 students marked late',
    adminNotif1Time: '2 minutes ago',
    adminNotif2Time: '8 minutes ago',
    adminNotif3Time: '15 minutes ago',

    // Teacher Layout
    teacherPortal: 'Teacher Portal',
    teacherRole: 'Teacher',
    teacherSideNavOverview: 'Overview',
    teacherSideNavClasses: 'My Classes',
    teacherSideNavAttendance: 'Attendance',
    teacherSideNavReports: 'Reports',
    teacherLogout: 'Logout',
    teacherBreadcrumb: 'Teacher',
    teacherNotif1: 'Class CS-301 starts at 08:00',
    teacherNotif2: '2 students absent in previous session',

    // Student Layout
    studentPortal: 'Student Portal',
    studentRole: 'Student',
    studentSideNavOverview: 'Overview',
    studentSideNavHistory: 'Attendance History',
    studentLogout: 'Logout',
    studentGreetMorning: 'Good morning',
    studentGreetAfternoon: 'Good afternoon',
    studentGreetEvening: 'Good evening',
    studentId: 'Student ID',
    studentCode: 'Code',
    studentClass: 'Class',

    // Page titles
    pageTitleAdminOverview: 'Overview',
    pageTitleAdminAttendance: 'Attendance',
    pageTitleAdminClasses: 'Class Management',
    pageTitleAdminStudents: 'Student Management',
    pageTitleAdminReports: 'Reports',
    pageTitleAdminAlerts: 'Alerts & Security',
    pageTitleAdminSettings: 'Settings',
    pageTitleTeacherOverview: 'Teacher Overview',
    pageTitleTeacherClasses: 'My Classes',
    pageTitleTeacherAttendance: 'Start Attendance',
    pageTitleTeacherReports: 'Class Reports',
    pageTitleStudentOverview: 'My Overview',
    pageTitleStudentHistory: 'Attendance History',

    // Status badges
    statusPresent: 'Present',
    statusLate: 'Late',
    statusAbsent: 'Absent',
    statusRegistered: 'Registered',
    statusPending: 'Pending',
    statusSuccess: 'Success',
    statusFailed: 'Failed',

    // Admin Dashboard
    dashTotalStudents: 'Total Students',
    dashPresentToday: 'Present Today',
    dashLate: 'Late',
    dashAbsent: 'Absent',
    dashRateToday: 'Attendance rate today',
    dashVsYesterday: 'vs yesterday',
    dashOnTime: 'On Time',
    dashTrend: 'Attendance Trend (This Week)',
    dashDistribution: "Today's Distribution",
    dashOnTimeVsLate: 'On Time vs Late (This Week)',
    dashSecurityAlerts: 'Security Alerts',
    dashNewAlerts: 'new',
    dashRecentLogs: 'Recent Attendance Logs',
    dashViewAll: 'View all',
    dashCheckInNow: 'Check In Now',
    dashHighPeak: 'Peak',
    dashAlertUnknown: 'Unknown face detected at Camera A — Main Gate',
    dashAlertLiveness: 'Liveness check failed at Room 202',
    dashAlertSuspicious: 'Multiple suspicious attempts at Lab Building B',
    dashMinsAgo2: '2 minutes ago',
    dashMinsAgo8: '8 minutes ago',
    dashMinsAgo15: '15 minutes ago',
    dashViewAllAlerts: 'View all alerts →',
    dashStudent: 'Student',
    dashId: 'ID',
    dashClass: 'Class',
    dashEntryTime: 'Entry Time',
    dashStatus: 'Status',

    // Teacher Dashboard
    teacherHello: 'Hello,',
    teacherDept: 'Faculty of Information Technology',
    teacherStartBtn: 'Start Attendance',
    teacherClassesCount: 'Classes Today',
    teacherTotalStudents: 'Total Students',
    teacherPresent: 'Present',
    teacherAvgRate: 'Avg. Rate',
    teacherTodayClasses: "Today's Classes",
    teacherViewAll: 'View all',
    teacherWeeklyTrend: "This week's trend",
    teacherTodayAlerts: "Today's Alerts",
    teacherRecentLogs: 'Recent Logs',
    teacherStudents: 'students',
    teacherAttendanceRate: 'Attendance rate',
    teacherActive: '🟢 In Progress',
    teacherUpcoming: '🔵 Upcoming',
    teacherDone: '✓ Done',
    teacherTakeAttendance: 'Attend',
    teacherAlertAbsent: 'Pham Thi Dung absent without leave — CS-301',
    teacherAlertLate: '2 students more than 15 minutes late',
    teacherOnTime: 'on time',
    teacherLate: 'late',
    teacherAbsent: 'absent',

    // Student Dashboard
    studentWelcomeBack: 'Welcome back,',
    studentSemester: 'Semester HK2 — 2025/2026',
    studentMyRate: 'Attendance Rate',
    studentMonthlyTrend: 'Monthly Trend',
    studentRecentHistory: 'Recent Attendance History',
    studentViewAll: 'View all',
    studentOutstanding: 'Outstanding Student',
    studentPassed: 'Requirement met',
    studentAttention: 'Watch your rate',
    studentFullHistory: 'Full Attendance History',
    studentRegisterFace: 'Re-register Face',
    studentRegisterFaceDesc: 'Update your recognition data',
    studentPresent: 'Present',
    studentLate: 'Late',
    studentAbsent: 'Absent',
    studentTotal: 'Total Sessions',
    studentSessions: 'sessions',
    studentSubjectCS: 'Computer Science 301',
    studentSubjectMath: 'Advanced Mathematics 202',
    studentSubjectPhysics: 'Physics Lab 301',
    studentMethod: 'Face',
    studentNoMethod: '--',

    // Attendance page
    attendCameraTitle: 'Face Recognition Scanner',
    attendLive: 'LIVE',
    attendCameraOnline: 'Camera A — Online',
    attendGoodConn: 'Good connection',
    attendLivenessOn: 'Liveness: ON',
    attendedToday: 'attended today',
    attendClass: 'Class CS-301 · 08:00 – 09:30',
    attendStartBtn: 'Start Attendance',
    attendScanNextBtn: 'Scan Next Person',
    attendScanning: 'Scanning...',
    attendChecking: 'Checking...',
    attendResetBtn: 'Reset',
    attendDetecting: 'Detecting face...',
    attendLivenessCheck: 'Liveness check',
    attendVerifySuccess: 'Verification success',
    attendVerifyFailed: 'Verification failed',
    attendLivenessStep1: 'Blink slowly',
    attendLivenessStep2: 'Turn head slightly left',
    attendLivenessStep3: 'Turn head slightly right',
    attendGuideIdle: '📷 Click "Start Attendance" to begin session.',
    attendGuideScanning: '🔍 Detecting face... Look straight at the camera.',
    attendGuideLiveness: '👁 Follow the liveness check instructions below.',
    attendGuideFailed: '❌ Liveness check failed. Try again or contact your teacher.',
    attendInstructions: 'Instructions',
    attendLivenessSteps: 'VERIFICATION STEPS',
    attendSessionStats: 'Session Stats',
    attendScanned: 'Scanned',
    attendPresent: 'Present',
    attendAbsent: 'Absent',
    attendRecentRec: 'Recent Recognitions',
    attendSuccessMsg: 'has been marked Present successfully!',
    attendLivenessFailTitle: 'Liveness Check Failed',
    attendLivenessFailDesc: 'Please try again or contact your teacher.',
    attendStatusBar: 'Status Bar',
  },

  vi: {
    brandName: 'SmartAttend',
    brandTagline: 'Hệ thống Nhận diện Khuôn mặt',
    systemFull: 'Hệ thống Điểm danh Thông minh sử dụng Nhận diện Khuôn mặt và Phát hiện Sống động',

    navFeatures: 'Tính năng',
    navHowItWorks: 'Cách hoạt động',
    navUsers: 'Đối tượng',
    navPricing: 'Giá cả',
    navLogin: 'Đăng nhập',
    navGetStarted: 'Bắt đầu miễn phí',

    heroTitle1: 'Hệ thống Điểm danh',
    heroTitle2: 'Thông minh',
    heroTitle3: 'bằng AI',
    heroSubtitle: 'Nhận diện khuôn mặt tức thời · Kiểm tra sinh trắc học chống gian lận · Báo cáo thời gian thực. Giải pháp điểm danh hiện đại nhất cho trường học và doanh nghiệp.',
    heroCta1: 'Bắt đầu miễn phí',
    heroCta2: 'Xem demo',
    stat1Val: '500+', stat1Label: 'Trường học',
    stat2Val: '50K+', stat2Label: 'Học viên',
    stat3Val: '98.7%', stat3Label: 'Độ chính xác',
    stat4Val: '< 1s', stat4Label: 'Thời gian nhận diện',

    trustedBy: 'ĐƯỢC TIN DÙNG BỞI CÁC TỔ CHỨC HÀNG ĐẦU',

    featuresTag: 'TÍNH NĂNG',
    featuresTitle: 'Tất cả trong một nền tảng',
    featuresSubtitle: 'Từ nhận diện khuôn mặt đến báo cáo tự động — SmartAttend cung cấp mọi công cụ bạn cần để quản lý điểm danh hiệu quả.',
    feat1Title: 'Nhận diện Khuôn mặt AI',
    feat1Desc: 'Công nghệ nhận diện khuôn mặt tiên tiến với độ chính xác lên đến 98.7%, hoạt động trong mọi điều kiện ánh sáng.',
    feat2Title: 'Kiểm tra Sinh trắc học',
    feat2Desc: 'Phát hiện và ngăn chặn gian lận bằng cách xác minh người thật qua chuyển động tự nhiên như chớp mắt, nghiêng đầu.',
    feat3Title: 'Bảng điều khiển Thời gian thực',
    feat3Desc: 'Theo dõi điểm danh ngay lập tức với biểu đồ trực quan, thống kê theo lớp và cảnh báo thông minh.',
    feat4Title: 'Báo cáo & Phân tích',
    feat4Desc: 'Xuất báo cáo PDF/Excel chi tiết, phân tích xu hướng và dự báo tỷ lệ điểm danh cho từng lớp học.',
    feat5Title: 'Bảo mật Đa lớp',
    feat5Desc: 'Hệ thống mã hóa dữ liệu end-to-end, quản lý phân quyền theo vai trò: Quản trị, Giảng viên, Học viên.',
    feat6Title: 'Đa nền tảng',
    feat6Desc: 'Hoạt động trên mọi trình duyệt và thiết bị. Không cần cài đặt phần mềm, chỉ cần kết nối Internet.',

    howTag: 'CÁCH HOẠT ĐỘNG',
    howTitle: 'Điểm danh chỉ trong 3 giây',
    howSubtitle: 'Quy trình đơn giản, nhanh chóng và bảo mật cao.',
    step1Title: 'Mở Camera',
    step1Desc: 'Học viên đứng trước camera điểm danh. Hệ thống tự động phát hiện khuôn mặt trong vòng 1 giây.',
    step2Title: 'Xác minh Danh tính',
    step2Desc: 'AI kiểm tra sinh trắc học (chớp mắt, nghiêng đầu) để đảm bảo người thật, không phải ảnh hay video.',
    step3Title: 'Ghi nhận Điểm danh',
    step3Desc: 'Điểm danh được ghi nhận tức thời vào hệ thống, thông báo đến giảng viên và phụ huynh ngay lập tức.',

    usersTag: 'ĐỐI TƯỢNG SỬ DỤNG',
    usersTitle: 'Phù hợp cho mọi tổ chức',
    userSchoolName: 'Trường học',
    userSchoolDesc: 'Giải pháp hoàn chỉnh cho quản lý điểm danh học sinh từ mầm non đến THPT với tích hợp hệ thống quản lý trường.',
    userSchoolStat1: '500+ trường đang dùng', userSchoolStat2: 'Tiết kiệm 3h/ngày', userSchoolStat3: '99.2% phụ huynh hài lòng',
    userSchoolBadge: 'Phổ biến nhất',
    userUniName: 'Đại học & Cao đẳng',
    userUniDesc: 'Quản lý điểm danh sinh viên cho hàng nghìn lớp học, tích hợp với hệ thống LMS và cổng sinh viên.',
    userUniStat1: '120+ trường đại học', userUniStat2: 'Hỗ trợ 50.000+ SV', userUniStat3: 'API mở cho LMS',
    userUniBadge: 'Cao cấp',
    userCorpName: 'Doanh nghiệp',
    userCorpDesc: 'Hệ thống chấm công kết hợp nhận diện khuôn mặt cho văn phòng, nhà máy và trung tâm đào tạo doanh nghiệp.',
    userCorpStat1: '200+ doanh nghiệp', userCorpStat2: 'Tích hợp HR system', userCorpStat3: 'Báo cáo lương tự động',
    userCorpBadge: 'Doanh nghiệp',
    learnMore: 'Tìm hiểu thêm',

    testimonialsTag: 'ĐÁNH GIÁ',
    testimonialsTitle: 'Được yêu thích bởi hàng nghìn giáo viên',
    t1Role: 'Trưởng phòng CNTT, Đại học Quốc gia HN',
    t1Text: 'SmartAttend đã giúp chúng tôi tiết kiệm hơn 3 giờ mỗi ngày cho công tác điểm danh. Giao diện trực quan, dễ sử dụng cho cả giảng viên lớn tuổi.',
    t2Role: 'Giáo viên chủ nhiệm, Trường THPT Chu Văn An',
    t2Text: 'Học sinh không còn gian lận điểm danh nữa. Phụ huynh cũng rất yên tâm vì nhận được thông báo ngay khi con vắng học.',
    t3Role: 'Giám đốc HR, FPT Software',
    t3Text: 'Tích hợp dễ dàng với hệ thống HR của chúng tôi. Tính năng báo cáo rất mạnh, giúp tính lương chính xác và minh bạch hơn.',

    ctaBadge: 'Dùng thử miễn phí 30 ngày, không cần thẻ tín dụng',
    ctaTitle1: 'Bắt đầu ngay hôm nay',
    ctaTitle2: 'Miễn phí, không ràng buộc',
    ctaSubtitle: 'Tham gia cùng 500+ trường học và doanh nghiệp đang sử dụng SmartAttend. Thiết lập trong 5 phút.',
    ctaBtn1: 'Tạo tài khoản miễn phí',
    ctaBtn2: 'Đăng nhập hệ thống',

    footerProduct: 'Sản phẩm',
    footerCompany: 'Công ty',
    footerSupport: 'Hỗ trợ',
    footerAbout: 'Về chúng tôi',
    footerBlog: 'Blog',
    footerCareers: 'Tuyển dụng',
    footerPress: 'Báo chí',
    footerDocs: 'Tài liệu',
    footerHelp: 'Trung tâm trợ giúp',
    footerContact: 'Liên hệ',
    footerPrivacy: 'Chính sách bảo mật',
    footerDesc: 'Hệ thống điểm danh thông minh bằng AI cho trường học và doanh nghiệp Việt Nam.',
    allSystemsNormal: 'Tất cả hệ thống hoạt động bình thường',
    copyright: '© 2026 SmartAttend. Được phát triển tại Việt Nam 🇻🇳',

    loginWelcome: 'Chào mừng trở lại',
    loginSubtitle: 'Nhập thông tin tài khoản của bạn',
    loginEmail: 'Email',
    loginEmailPlaceholder: 'email@truonghoc.edu.vn',
    loginPassword: 'Mật khẩu',
    loginPassPlaceholder: '••••••••',
    loginForgot: 'Quên mật khẩu?',
    loginBtn: 'Đăng nhập',
    loginNoAccount: 'Chưa có tài khoản?',
    loginRegisterLink: 'Đăng ký ngay',
    loginDemoLabel: '⚡ ĐĂNG NHẬP DEMO NHANH',
    loginDemoAdmin: 'Quản trị viên',
    loginDemoTeacher: 'Giảng viên',
    loginDemoStudent: 'Học viên',
    loginDemoOnClick: '1-click demo',
    loginError: 'Email hoặc mật khẩu không đúng. Hãy dùng tài khoản demo bên dưới.',
    loginBrandFeature1Title: 'Bảo mật cao',
    loginBrandFeature1Desc: 'Mã hóa dữ liệu end-to-end',
    loginBrandFeature2Title: 'Dễ sử dụng',
    loginBrandFeature2Desc: 'Giao diện trực quan cho mọi người',
    loginBrandFeature3Title: 'Thời gian thực',
    loginBrandFeature3Desc: 'Cập nhật điểm danh tức thời',
    loginAsRole: 'Đang đăng nhập với tư cách',
    loginAllSystems: 'Tất cả hệ thống hoạt động bình thường',

    registerStep1: 'Chọn vai trò',
    registerStep2: 'Thông tin cá nhân',
    registerStep3: 'Đăng ký khuôn mặt',
    registerStepOf: 'Bước',
    registerStepOf2: 'trên 3:',
    registerWhoAreYou: 'Bạn là ai?',
    registerWhoDesc: 'Chọn vai trò để chúng tôi thiết lập tài khoản phù hợp cho bạn.',
    registerRoleStudent: 'Học viên / Sinh viên',
    registerRoleStudentDesc: 'Xem lịch sử điểm danh, theo dõi tỷ lệ có mặt của bản thân.',
    registerRoleTeacher: 'Giảng viên / Giáo viên',
    registerRoleTeacherDesc: 'Quản lý điểm danh lớp học, xem báo cáo và bắt đầu phiên điểm danh.',
    registerCreateAccount: 'Tạo tài khoản',
    registerAccount: '',
    registerFillInfo: 'Điền đầy đủ thông tin bên dưới',
    registerName: 'Họ và tên',
    registerNamePH1: 'TS. Nguyễn Văn A',
    registerNamePH2: 'Nguyễn Thị B',
    registerEmail: 'Email',
    registerEmailPH: 'email@truonghoc.edu.vn',
    registerFaculty: 'Khoa / Bộ môn',
    registerFaculty1: 'Khoa Công nghệ Thông tin',
    registerFaculty2: 'Khoa Kinh tế',
    registerFaculty3: 'Khoa Ngoại ngữ',
    registerFaculty4: 'Khoa Kỹ thuật',
    registerClassCode: 'Mã lớp học',
    registerClassPH: 'CS-301',
    registerPassword: 'Mật khẩu',
    registerPasswordPH: 'Tối thiểu 8 ký tự',
    registerConfirmPass: 'Xác nhận mật khẩu',
    registerConfirmPH: 'Nhập lại mật khẩu',
    registerCreateBtn: 'Tạo tài khoản',
    registerPassMismatch: 'Mật khẩu xác nhận không khớp.',
    registerBack: 'Quay lại',
    registerAlreadyHave: 'Đã có tài khoản?',
    registerLoginLink: 'Đăng nhập',
    registerFaceTitle: 'Đăng ký khuôn mặt',
    registerFaceDesc: 'Đăng ký khuôn mặt để sử dụng tính năng điểm danh tự động. Bạn có thể bỏ qua bước này và thực hiện sau.',
    registerFaceBtn: 'Bật camera đăng ký ngay',
    registerFaceSkip: 'Bỏ qua, đăng ký sau',
    registerTerms: 'Bằng cách đăng ký, bạn đồng ý với',
    registerTermsLink: 'Điều khoản dịch vụ',
    registerAnd: 'và',
    registerPrivacyLink: 'Chính sách bảo mật',

    adminRole: 'Quản trị viên',
    adminLoggedInAs: 'Đang đăng nhập với tư cách',
    adminSideNavOverview: 'Tổng quan',
    adminSideNavAttendance: 'Điểm danh',
    adminSideNavClasses: 'Lớp học',
    adminSideNavStudents: 'Học viên',
    adminSideNavReports: 'Báo cáo',
    adminSideNavAlerts: 'Cảnh báo',
    adminSideNavSettings: 'Cài đặt',
    adminLogout: 'Đăng xuất',
    adminBreadcrumbHome: 'Trang chủ',
    adminNotifTitle: 'Thông báo',
    adminMarkRead: 'Đánh dấu đã đọc',
    adminNotif1: 'Phát hiện khuôn mặt lạ — Camera A',
    adminNotif2: 'Kiểm tra sinh trắc thất bại — Phòng 202',
    adminNotif3: '3 học viên được đánh dấu muộn',
    adminNotif1Time: '2 phút trước',
    adminNotif2Time: '8 phút trước',
    adminNotif3Time: '15 phút trước',

    teacherPortal: 'Cổng Giảng viên',
    teacherRole: 'Giảng viên',
    teacherSideNavOverview: 'Tổng quan',
    teacherSideNavClasses: 'Lớp của tôi',
    teacherSideNavAttendance: 'Điểm danh',
    teacherSideNavReports: 'Báo cáo',
    teacherLogout: 'Đăng xuất',
    teacherBreadcrumb: 'Giảng viên',
    teacherNotif1: 'Lớp CS-301 bắt đầu lúc 08:00',
    teacherNotif2: 'Có 2 học viên vắng trong buổi trước',

    studentPortal: 'Cổng Học viên',
    studentRole: 'Học viên',
    studentSideNavOverview: 'Tổng quan',
    studentSideNavHistory: 'Lịch sử điểm danh',
    studentLogout: 'Đăng xuất',
    studentGreetMorning: 'Chào buổi sáng',
    studentGreetAfternoon: 'Chào buổi chiều',
    studentGreetEvening: 'Chào buổi tối',
    studentId: 'Mã học viên',
    studentCode: 'Mã',
    studentClass: 'Lớp',

    pageTitleAdminOverview: 'Tổng quan',
    pageTitleAdminAttendance: 'Điểm danh',
    pageTitleAdminClasses: 'Quản lý Lớp học',
    pageTitleAdminStudents: 'Quản lý Học viên',
    pageTitleAdminReports: 'Báo cáo',
    pageTitleAdminAlerts: 'Cảnh báo & Bảo mật',
    pageTitleAdminSettings: 'Cài đặt',
    pageTitleTeacherOverview: 'Tổng quan Giảng viên',
    pageTitleTeacherClasses: 'Lớp học của tôi',
    pageTitleTeacherAttendance: 'Bắt đầu Điểm danh',
    pageTitleTeacherReports: 'Báo cáo Lớp học',
    pageTitleStudentOverview: 'Tổng quan của tôi',
    pageTitleStudentHistory: 'Lịch sử Điểm danh',

    statusPresent: 'Có mặt',
    statusLate: 'Muộn',
    statusAbsent: 'Vắng',
    statusRegistered: 'Đã đăng ký',
    statusPending: 'Chờ duyệt',
    statusSuccess: 'Thành công',
    statusFailed: 'Thất bại',

    dashTotalStudents: 'Tổng học viên',
    dashPresentToday: 'Có mặt hôm nay',
    dashLate: 'Đến muộn',
    dashAbsent: 'Vắng mặt',
    dashRateToday: 'Tỷ lệ điểm danh hôm nay',
    dashVsYesterday: 'so với hôm qua',
    dashOnTime: 'Đúng giờ',
    dashTrend: 'Xu hướng điểm danh (Tuần này)',
    dashDistribution: 'Phân bố hôm nay',
    dashOnTimeVsLate: 'Đúng giờ vs Muộn (Tuần này)',
    dashSecurityAlerts: 'Cảnh báo bảo mật',
    dashNewAlerts: 'mới',
    dashRecentLogs: 'Nhật ký điểm danh gần đây',
    dashViewAll: 'Xem tất cả',
    dashCheckInNow: 'Điểm danh ngay',
    dashHighPeak: 'Cao điểm',
    dashAlertUnknown: 'Phát hiện khuôn mặt lạ tại Camera A — Cổng chính',
    dashAlertLiveness: 'Kiểm tra sinh trắc thất bại tại Phòng 202',
    dashAlertSuspicious: 'Nhiều lần thử đáng ngờ tại Tòa nhà Lab B',
    dashMinsAgo2: '2 phút trước',
    dashMinsAgo8: '8 phút trước',
    dashMinsAgo15: '15 phút trước',
    dashViewAllAlerts: 'Xem tất cả cảnh báo →',
    dashStudent: 'Học viên',
    dashId: 'Mã số',
    dashClass: 'Lớp',
    dashEntryTime: 'Giờ vào',
    dashStatus: 'Trạng thái',

    teacherHello: 'Xin chào,',
    teacherDept: 'Khoa Công nghệ Thông tin',
    teacherStartBtn: 'Bắt đầu điểm danh',
    teacherClassesCount: 'Lớp hôm nay',
    teacherTotalStudents: 'Tổng học viên',
    teacherPresent: 'Có mặt',
    teacherAvgRate: 'Tỷ lệ TB',
    teacherTodayClasses: 'Lớp học hôm nay',
    teacherViewAll: 'Xem tất cả',
    teacherWeeklyTrend: 'Xu hướng tuần này',
    teacherTodayAlerts: 'Cảnh báo hôm nay',
    teacherRecentLogs: 'Nhật ký điểm danh gần đây',
    teacherStudents: 'SV',
    teacherAttendanceRate: 'Tỷ lệ điểm danh',
    teacherActive: '🟢 Đang diễn ra',
    teacherUpcoming: '🔵 Sắp tới',
    teacherDone: '✓ Đã xong',
    teacherTakeAttendance: 'Điểm danh',
    teacherAlertAbsent: 'Phạm Thị Dung vắng không phép — CS-301',
    teacherAlertLate: '2 học viên đến muộn > 15 phút',
    teacherOnTime: 'có mặt',
    teacherLate: 'muộn',
    teacherAbsent: 'vắng',

    studentWelcomeBack: 'Chào mừng trở lại,',
    studentSemester: 'HK2 — 2025/2026',
    studentMyRate: 'Tỷ lệ điểm danh',
    studentMonthlyTrend: 'Tỷ lệ theo tháng',
    studentRecentHistory: 'Lịch sử điểm danh gần đây',
    studentViewAll: 'Xem tất cả',
    studentOutstanding: 'Học viên xuất sắc',
    studentPassed: 'Đạt yêu cầu',
    studentAttention: 'Chú ý tỷ lệ',
    studentFullHistory: 'Lịch sử điểm danh đầy đủ',
    studentRegisterFace: 'Đăng ký lại khuôn mặt',
    studentRegisterFaceDesc: 'Cập nhật dữ liệu nhận diện của bạn',
    studentPresent: 'Có mặt',
    studentLate: 'Muộn',
    studentAbsent: 'Vắng',
    studentTotal: 'Tổng buổi học',
    studentSessions: 'buổi',
    studentSubjectCS: 'Khoa học Máy tính 301',
    studentSubjectMath: 'Toán Nâng cao 202',
    studentSubjectPhysics: 'Vật lý Thực hành 301',
    studentMethod: 'Khuôn mặt',
    studentNoMethod: '--',

    attendCameraTitle: 'Máy quét Nhận diện Khuôn mặt',
    attendLive: 'TRỰC TIẾP',
    attendCameraOnline: 'Camera A — Trực tuyến',
    attendGoodConn: 'Kết nối tốt',
    attendLivenessOn: 'Sinh trắc học: BẬT',
    attendedToday: 'đã điểm danh hôm nay',
    attendClass: 'Lớp CS-301 · 08:00 – 09:30',
    attendStartBtn: 'Bắt đầu điểm danh',
    attendScanNextBtn: 'Quét người tiếp theo',
    attendScanning: 'Đang quét...',
    attendChecking: 'Đang kiểm tra...',
    attendResetBtn: 'Đặt lại',
    attendDetecting: 'Phát hiện khuôn mặt...',
    attendLivenessCheck: 'Kiểm tra sinh trắc',
    attendVerifySuccess: 'Xác minh thành công',
    attendVerifyFailed: 'Kiểm tra thất bại',
    attendLivenessStep1: 'Chớp mắt chậm',
    attendLivenessStep2: 'Quay đầu nhẹ sang trái',
    attendLivenessStep3: 'Quay đầu nhẹ sang phải',
    attendGuideIdle: '📷 Nhấn "Bắt đầu điểm danh" để bắt đầu phiên.',
    attendGuideScanning: '🔍 Đang phát hiện khuôn mặt... Nhìn thẳng vào camera.',
    attendGuideLiveness: '👁 Thực hiện theo hướng dẫn sinh trắc học bên dưới.',
    attendGuideFailed: '❌ Kiểm tra sinh trắc thất bại. Thử lại hoặc báo giảng viên.',
    attendInstructions: 'Hướng dẫn',
    attendLivenessSteps: 'CÁC BƯỚC KIỂM TRA',
    attendSessionStats: 'Thống kê phiên',
    attendScanned: 'Đã quét',
    attendPresent: 'Có mặt',
    attendAbsent: 'Vắng',
    attendRecentRec: 'Nhận diện gần đây',
    attendSuccessMsg: 'đã được ghi nhận Có mặt thành công!',
    attendLivenessFailTitle: 'Kiểm tra sinh trắc thất bại',
    attendLivenessFailDesc: 'Vui lòng thử lại hoặc liên hệ giảng viên.',
    attendStatusBar: 'Thanh trạng thái',
  },
} as const;

type TranslationKeys = keyof typeof translations.en;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKeys) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'en',
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    try {
      return (localStorage.getItem('smartattend_lang') as Lang) || 'en';
    } catch {
      return 'en';
    }
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('smartattend_lang', l);
  };

  const t = (key: TranslationKeys): string => {
    return (translations[lang] as Record<string, string>)[key] ?? (translations.en as Record<string, string>)[key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
